version: "3.8"

services:
  pdv:
    image: ghcr.io/alexconectado/pdv-caixa:latest
    hostname: "{{.Service.Name}}.{{.Task.Slot}}"
    environment:
      - SECRET_KEY=change-this-secret-key-in-production
      - DATABASE_URL=sqlite:////data/pdv.db
    volumes:
      - pdv_data:/data
    networks:
      - traefik_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        # Router / domínio
        - traefik.http.routers.pdv.rule=Host(`pdv.brostech3d.com.br`)
        - traefik.http.routers.pdv.entrypoints=websecure
        - traefik.http.routers.pdv.tls=true
        - traefik.http.routers.pdv.tls.certresolver=letsencryptresolver
        # Serviço interno na porta 8000
        - traefik.http.services.pdv.loadbalancer.server.port=8000
        - traefik.http.routers.pdv.service=pdv
        - traefik.http.services.pdv.loadbalancer.passhostheader=true
        # Informe explicitamente a rede do Traefik (importante em Swarm)
        - traefik.docker.network=network_public
        # Middleware para headers SSL (útil para websockets/forwarded proto)
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.pdv.middlewares=sslheader@docker
        # (Opcional) Redirect HTTP -> HTTPS
        - traefik.http.routers.pdv-web.rule=Host(`pdv.brostech3d.com.br`)
        - traefik.http.routers.pdv-web.entrypoints=web
        - traefik.http.routers.pdv-web.middlewares=redirect-to-https@docker
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

volumes:
  pdv_data:
    driver: local

networks:
  traefik_network:
    external: true
    name: network_public
